# redis数据库连接配置(covert)
jedisconfig:
  url: "redis://:120.197.17.151:22002/"
  # 最大实例数
  maxTotal: 100
  # 最大空闲实例数
  maxIdle: 10
  # (创建实例时)最大等待时间
  maxWaitMillis: 10000
  # (创建实例时)是否验证
  testOnBorrow: true
  
  
rocketmq:
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: vehicleProducerGroup
    #mq的nameserver地址
    namesrvAddr: 103.40.102.157:9876
    #如果需要同一个jvm中不同的producer往不同的mq集群发送消息，需要设置不同的instanceName
    instanceName: vehicleProducer
    #topic名称
    topic: TEST
    #根据实际情况设置消息的tag
    tag: TEST
    #消息最大长度
    maxMessageSize: 131072 # 1024*128
    #发送消息超时时间
    sendMsgTimeout: 10000
  consumer:
    namesrvAddr: 103.40.102.157:9876
    groupName: vehicleProducerGroup
    topic: sms
    tag: verifycode
    consumeThreadMin: 20
    consumeThreadMax: 64
    
    
 # Server Url
http:
  server:
    deploy : "wx.10086.cn"
    local: "221.176.66.251"
    processId : 9000
#wechat
wechat:
   appid : "wx2e7288fdd5f458b7"
   accountId : "5109afce-6b8f-4e9f-b706-36e7bf3e2f39"
   cmcc : "https://kfol.cmcc-cs.cn/ngmmgw/channelapi/web/index/"
   
#mongodb
spring:  
  data:  
    mongodb:  
      uri: mongodb://120.197.17.151:22001/wxcrm  